apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-verse-backend
  namespace: event-verse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-verse-backend
  template:
    metadata:
      labels:
        app: event-verse-backend
    spec:
      containers:
        - name: event-verse-backend
          image: usmanali2005/event-verse-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://localhost:27017/event-verse-main"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
