apiVersion: v1
kind: Service
metadata:
  name: event-verse-backend-service
  namespace: event-verse
spec:
  type: NodePort
  selector:
    app: event-verse-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
