apiVersion: v1
kind: Service
metadata:
  name: event-verse-frontend-service
  namespace: event-verse
spec:
  type: NodePort
  selector:
    app: event-verse-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
