apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: event-verse
spec:
  type: ClusterIP
  selector:
    app: mongodb-service
  ports:
    - port: 27017
      targetPort: 27017
