name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker to use Minikube's environment
      shell: powershell
      run: |
       & minikube -p minikube docker-env --shell powershell | Invoke-Expression


      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -f app/frontend/Dockerfile -t usmanali2005/event-verse-frontend:latest .
          docker push usmanali2005/event-verse-frontend:latest

      - name: Build and Push Backend Docker Image
        run: |
          docker build -f app/backend/Dockerfile -t usmanali2005/event-verse-backend:latest .
          docker push usmanali2005/event-verse-backend:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/mongodb-deployment.yaml
          kubectl apply -f k8s/mongodb-service.yaml
